apiVersion: v1
kind: Pod
metadata:
  labels:
    qos.coreweave.cloud/latency: low
  name: ppo-trainer-ziyi-run-9
  namespace: tenant-chairesearch-test
spec:
  volumes:
    - name: model-storage
      persistentVolumeClaim:
        claimName: model-storage
  imagePullSecrets:
      - name: docker-creds
  containers:
    - name: ppo-trainer-container-ziyi-run-9
      image: gcr.io/chai-959f8/training:ppo-trainer-ziyi
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "1"
          nvidia.com/gpu: "1"
          memory: 124Gi
        requests:
          cpu: "1"
          nvidia.com/gpu: "1"
          memory: 124Gi
      volumeMounts:
        - name: model-storage
          mountPath: /models
      env:
        - name: RUN_NAME
          value: "run-gpt-neo-1.3B"
        - name: PROJECT_NAME
          value: "gpt2-large-ppo"
        - name: MODEL_NAME
          value: "EleutherAI/gpt-neo-1.3B"
        - name: TOKENIZER_NAME
          value: "EleutherAI/gpt-neo-1.3B"
        - name: REF_MODEL_NAME
          value: "hakurei/litv2-6B-rev2"
        - name: BATCH_SIZE
          value: "16"
        - name: FP16
          value: "True"
        - name: ADAP_KL_CTRL
          value: "True"
        - name: INIT_KL_COEF
          value: "0.05"
        - name: TARGET
          value: "10"
        - name: HORIZON
          value: "10000"
        - name: STORAGE_URI
          value: pvc://model-storage/
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/ready
        failureThreshold: 1
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 5
          preference:
            matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                  - ORD1
        - weight: 20
          preference:
            matchExpressions:
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - A100_PCIE_80GB
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - A100_PCIE_80GB
